### ISSUE TITLE
More info about Model

### ISSUE THREAD

**Issue by thejw23** [mossphp/moss-storage#20]
I try to set up sample code to see how Moss Storage would work with Slim. Could you provide more info about models, to use Moss with regular MVC framework?

**Comment by potfur** [comment]
This is the [database structure](https://gist.github.com/potfur/9a67c9adade6f0f49bfc) that I use while migrating to [DBAL](https://github.com/potfur/moss-storage/tree/dbal).

Whole structure exactly the same, with only minor differences like `Serial` became `Blob` and `auto_increment` is now `autoincrement`.

**Comment by thejw23** [comment]
Thanks for the gist, this is what I needed.
